### ISSUE TITLE
long values give integer error on javarepl.com

### ISSUE THREAD

**Issue by destan** [albertlatacz/java-repl#114]
```
java> long l = 1485620920109
ERROR: integer number too large: 1485620920109
     1485620920109;
     ^
java> Long l = new Long(1485620920109)
ERROR: integer number too large: 1485620920109
     new Long(1485620920109);
              ^
```

![image](https://cloud.githubusercontent.com/assets/442813/22398129/ec5553d6-e589-11e6-9589-ddc8183cb7c3.png)

**Comment by ebanisadr** [comment]
This probably won't help you but that's not a REPL error. Your code is bad because you used `int` literals to represent `long` numbers. Usually that is fine due to Java's automatic broadening (i.e. 2.5/5 = 0.5000...), but your literal is not valid. Convert them to `long` literals to make them work by adding an `L` at the end:

`integer number too large: 1485620920109L`

`Long l = new Long(1485620920109L)`

![image](https://cloud.githubusercontent.com/assets/24218339/23395932/009fc65e-fd46-11e6-9d38-5cad19affc6c.png)

**Comment by destan** [comment]
thanks for the answer.

and yes  _"my code is bad"_ 

> Values of the integral types byte, short, int, and long can be created from int literals. Values of type long that exceed the range of int can be created from long literals.

https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html
