### ISSUE TITLE
No auto-complete on non-core libs?

### ISSUE THREAD

**Issue by patcon** [albertlatacz/java-repl#69]
I loaded a library onto the classpath and I'm not able to find it via tab-complete. Is that expected? Was hoping I could use this tool to help explore new libraries, like I do with iPython :)

Thanks!

**Comment by saikrishna321** [comment]
@albertlatacz any help on this ?

**Comment by albertlatacz** [comment]
This should be fixed in latest version

try using :cp e.g. <code>
:cp http://repo1.maven.org/maven2/joda-time/joda-time/2.9.6/joda-time-2.9.6.jar
</code> to import libraries

<img width="1589" alt="screen shot 2016-12-02 at 21 22 49" src="https://cloud.githubusercontent.com/assets/2648270/20850958/a7cd5b5e-b8d5-11e6-8e23-3ef97c720236.png">
