### ISSUE TITLE
Publish jars on maven central

### ISSUE THREAD

**Issue by chirino** [albertlatacz/java-repl#79]

**Comment by alexarchambault** [comment]
:+1:

**Comment by chipsenkbeil** [comment]
Found this when someone asked about Java support on Apache Toree (http://toree.incubator.apache.org/). Having a published jar would definitely be the first step to being able to consume this in other projects. Would also enable a Jupyter kernel (#93) if we consumed it since Apache Toree's main component is a Jupyter kernel.

**Comment by bzz** [comment]
+1 for publishing it

**Comment by jasonwyatt** [comment]
👍  This would be awesome

**Comment by iemejia** [comment]
Any further progress in this one ? I am discussing some integration  with Apache Zeppelin and this would be needed in that direction.

**Comment by albertlatacz** [comment]
It's now released to both JCenter and Maven Central
